/// @description set up variables

// STATIC VARIABLES
PLAYER_MAX_WALK_SPEED = 1
PLAYER_ACCELERATION = 0.2
PLAYER_GROUND_FRICTION = 1.3
PLAYER_TERMINAL_VELOCITY = 20

PLAYER_JUMP_FORCE = 2.5
PLAYER_DOUBLE_JUMP_FORCE = 2
PLAYER_SPRING_JUMP_FORCE = 4.2
PLAYER_JUMP_MODIFIER = 1.1

DEATHS = 0

GRAVITY_FORCE = 0.2
